# Generated by Django 4.0 on 2023-11-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_slug'),
        ('recipes', '0002_auto_20211130_0929'),
    ]

    operations = [
    ]
